name: Trash Mining

on:
  workflow_dispatch: {}

jobs:
  mine-popcornnews:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: browser-actions/setup-geckodriver@latest
      - run: pip install -r mining/requirements.txt

      - run: cd mining && python main.py 7
      - uses: actions/upload-artifact@v2
        name: Upload dataset
        if: always()
        with:
          name: dataset
          path: mining/output
